server:
  port: 1040 # Default port for Spring Boot. Change if required.
 address: 0.0.0.0  # Listen on all interfacess

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iv_dakshabhi_com?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8
    username: root
    password: w9jhZMTGVnzWWGR1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Other options: create, create-drop, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # For MySQL 8 and above. Use MySQL5Dialect for older versions
    show-sql: true # Displays generated SQL statements in the console (optional).
    generate-ddl: true # Ensures schema generation
  application:
    name: iv

# ✅ Allow Cross-Origin Requests
cors:
  allowed-origins: "https://iv.dakshabhi.com/"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "*"
